server:
  port: ${PORT:8541}

spring:
  oauth2:
    resource:
        userInfoUri: http://localhost:9999/uaa/user

  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-service