server:
  port: ${PORT:9999}
  contextPath: /uaa

security:
  user:
    password: password

spring:
  cloud:
    config:
      server:
        git :
          uri: https://github.com/joshlong/microservices-lab-configuration